In [66]:
# loans (of the sr manzano collection) expiring in the next 36 hours
import pandas as pd
import datetime
import timedelta

In [67]:
df = pd.read_csv('data/nft-sr-m.csv', header=0, index_col=False).astype('object')

In [68]:
span_start = datetime.datetime.now() - timedelta.Timedelta(days=7)
span_end = datetime.datetime.now() - timedelta.Timedelta(days=7, hours=-36)
span_start_unix = int(span_start.timestamp())
span_end_unix = int(span_end.timestamp())
df_slice = df.query(f'op_3.isnull() and op_2!="Rescind" and op_2.notnull() and b_time_2>={span_start_unix} and b_time_2<={span_end_unix}').copy().sort_values(['b_time_2'], ascending=[False]).reset_index(drop=True)
df_slice.index += 1

In [69]:
df_slice

,loan,lender,borrower,asset,amount,op_2,op_3,b_time_1,b_time_2,b_time_3,tx_1,tx_2,tx_3
1,AZCfDqyyJWfRiYhhFmewaP2iBoW8cQoUp5R3hLRyAoV9,DGLKFnZu9mcD8J86NS8KKEf5Y7mYjL3zBh8Ny5WhbtgA,DtfMyW5qURGxMQtCu7dyTMmLnDqP4hgL4ur3sKUsc81v,DJx58HrvxkAJH1ZAH47aKzpF3wAEtj3c5vAUkGcJVK8j,310953520,Extend,NaN,1748724069,1748894003.0,NaN,3d9wqrBuhz55L78DmUyFCy8cruuf2kaLyFLHdzQNowFMzu...,2Y8dQdgMrR4XXkocNPBSZQrRSECr7PfFnqmo55vJ5U3Tv7...,NaN
2,63pp97wVBb34ZiAx8Jcep8YiQANQf6GVoSG8XWaraJLN,H9ko65q5RzfVCPLoti1FE1EP5cjh83UN6gBAqXXHkP3M,DtfMyW5qURGxMQtCu7dyTMmLnDqP4hgL4ur3sKUsc81v,Q2eZrAfYiVBmkwdr4xqi7HUNQHUTza5jsj6E8aUYUc1,450953520,Extend,NaN,1748841050,1748894003.0,NaN,3MkJNAR8bQ9kY4ScDujaXZZHJ98ZSstcZfiyJA7EHVtc2t...,2n6xC53hTjYyn83awZJayYuZb6GQk3kLVhLVFnebhQKhKn...,NaN
3,6SGbu2cv8KMGTLiN9Gf5G5SJbmdb9YFsry4YzwL8wn6H,H9ko65q5RzfVCPLoti1FE1EP5cjh83UN6gBAqXXHkP3M,DtfMyW5qURGxMQtCu7dyTMmLnDqP4hgL4ur3sKUsc81v,AdNBmWpKRTf8pHMvr3tHfcEmgbLtUw4BsbffhZm6rFiP,450953520,Extend,NaN,1748841050,1748894003.0,NaN,3MkJNAR8bQ9kY4ScDujaXZZHJ98ZSstcZfiyJA7EHVtc2t...,2LLsCrrmi68zBDLcQUtPb9mJR2X1QvPSnjkcH4JsZASBPx...,NaN
4,DPRf8wTzMnpD1q9KyByUTrZkyo43jkxeafTMubnhK18D,H9ko65q5RzfVCPLoti1FE1EP5cjh83UN6gBAqXXHkP3M,DtfMyW5qURGxMQtCu7dyTMmLnDqP4hgL4ur3sKUsc81v,ARdZJL1x4wbCeu8yANQJpWw5qbETMVnDy7X8odAxkSUr,450953520,Extend,NaN,1748841050,1748894003.0,NaN,3MkJNAR8bQ9kY4ScDujaXZZHJ98ZSstcZfiyJA7EHVtc2t...,3utdewPo7m32Uzv4SB7iR1StaRfatqRTM46DcL5dzQjPfu...,NaN
5,5rQd11u4GaeLAcYD47RgqttfY8NH5SUc4TQhctGfF5mA,DGLKFnZu9mcD8J86NS8KKEf5Y7mYjL3zBh8Ny5WhbtgA,DtfMyW5qURGxMQtCu7dyTMmLnDqP4hgL4ur3sKUsc81v,BqXbJx6j51mXftFPVaAiBB8c1gtoFzm6GtCUqjXXV2Ry,320953520,Extend,NaN,1748886781,1748894003.0,NaN,4BsQgjfc1gBo1dFq2hoamdGeHs8ZvQpPfYnKfPHawJy6qp...,3jQUUAUTQ5qr3hrwB3KTBJ1M61zQrEtxN3WR7RqLy7PZyX...,NaN
6,9A4gDUvttv9UgsWCLMnGpDKcpAbi2BnXdJcvA5UPFD6y,FRiKTTtBFCraXxAdN9WbE9gHsJHauHzLKf2t53xiyFRR,3fAULNcyH95wcCuvKdCuFBcng5PoDzqEWMmpQ4WBWf72,3TMJHtLqV7oGEzRbFUDzecvBuTFqHhKYRkcZpHDabTib,460953520,Extend,NaN,1748851816,1748893258.0,NaN,4Yg9cR3EPRgV5Z8HsdhYbZxNVcSXDNgEsJQVy9hZS5G2gY...,4ACodnz9NXXkbo5MVxDZwKCFVRaKZgX5kYAx3MmPWLeo3t...,NaN

In [70]:
# borrower + hours_left
df_slice.loc[:, ['borrower_readable']]  = df_slice['borrower'].str[0:3] + '___' + df_slice['borrower'].str[-3:]
df_slice.loc[:, ['hours_left']] = round((df_slice['b_time_2'].astype(int) - span_start_unix)/60/60).astype(int)

In [71]:
df_slice[['borrower_readable', 'hours_left']]

  borrower_readable  hours_left
1         Dtf___81v          32
2         Dtf___81v          32
3         Dtf___81v          32
4         Dtf___81v          32
5         Dtf___81v          32
6         3fA___f72          31